### ISSUE TITLE
JAR TODO

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/dafny#3]
- [x] merge the latest Dafny(2019)
- [x] update to VS2017
- [ ] test the merged version with dafny test beds and tactic examples.
- [ ] double check the dafny examples in the paper can still work for the latest dafny
- [ ] fix _explore_ syntax
- [ ] setup paper examples and resources
- [ ] run experiments to collect the number of examples which the tactic _$3.5 Variants_ can capture
- [ ] in _$3.6_ to provide an exmaple to illustrate the debugging support
- [ ] go over semantics to double check the implementation conforms to the semantics
- [ ] check VS code implemetation
- [ ] check VS IDE

**Comment by lyhlbyl** [comment]
bug: f there is "assert false" in tac,  tacny would consider the error is outside of tac. This is caused by copystmt which copy the original tok line number.
